Assignment:T17
karthick-1205/Assignments pull request #24
Opened 2023-08-28 10:10 UTC by karthick-1205

2023-10-13 09:27 UTC, priyarathna requested changes

2023-10-13 09:27 UTC, priyarathna commented on MainRepository/Program.cs
> +HashSet<string> result = GetPermutations (str);
@karthick-1205 : Why 'Hash' is used?

2023-10-13 09:27 UTC, priyarathna commented on MainRepository/Program.cs
> +   if (str.Length == 0) {
If it's an empty string, then print the appropriate message.

2023-10-18 09:20 UTC, karthick-1205 commented on MainRepository/Program.cs
> +HashSet<string> result = GetPermutations (str);
Remove duplicate string.

2023-10-20 04:28 UTC, priyarathna requested changes

2023-10-20 04:28 UTC, priyarathna commented on MainRepository/Program.cs
> +   if (str.Length == 0) {
@karthick-1205 : Not yet handled.

2023-10-25 09:46 UTC, priyarathna approved these changes

2023-10-25 09:46 UTC, closed without merging