Assignment:T04
karthick-1205/Assignments pull request #3
Opened 2023-08-14 12:01 UTC by karthick-1205

2023-10-04 04:08 UTC, sdinesh-90 requested changes

2023-10-04 04:08 UTC, sdinesh-90 commented on MainRepository/Program.cs
> +n1 = Convert.ToInt32 (Console.ReadLine ());
You TryParse to validate the input.

2023-10-04 04:08 UTC, sdinesh-90 commented on MainRepository/Program.cs
> +int n1, n2, x, y, temp, gcd, lcm;
Declare variables when you are staring to use.
In this case n1 should be declared at line 4, n2 at line 6, x at line 7, y at line 8, temp at line 10, gcd at line 14 and lcm at line 15.

2023-10-04 04:11 UTC, sdinesh-90 commented
@karthick-1205 I am finding difficult to understand the logic. Can you please explain in detail how you compute GCM?

2023-10-12 09:14 UTC, karthick-1205 commented
> @karthick-1205 I am finding difficult to understand the logic. Can you please explain in detail how you compute GCM?
 Euclidian algorithm
https://www.freecodecamp.org/news/euclidian-gcd-algorithm-greatest-common-divisor/

2023-10-12 09:48 UTC, sdinesh-90 requested changes

2023-10-12 09:48 UTC, sdinesh-90 commented on MainRepository/Program.cs
> +int y = n2;
```suggestion
int x = n1, y = n2;

```

2023-10-12 09:48 UTC, sdinesh-90 commented on MainRepository/Program.cs
> +   while (int.TryParse (response, out number) && number <= 0);
Try to use while instead of do while.

2023-10-13 03:27 UTC, sdinesh-90 requested changes

2023-10-13 03:27 UTC, sdinesh-90 commented on MainRepository/Program.cs
> +   while (!int.TryParse (response, out number) || number <= 0) {
Instead of response variable and declaring type of number, you could directly call int.TryParse (Console.ReadLine (), out int number).

2023-10-13 06:53 UTC, sdinesh-90 requested changes

2023-10-13 06:53 UTC, sdinesh-90 commented on MainRepository/Program.cs
> +      Console.Write (message);
After break, else is not needed.

2023-10-13 14:09 UTC, sdinesh-90 approved these changes

2023-10-13 14:09 UTC, sdinesh-90 commented on MainRepository/Program.cs
> +int lcm = (n1 * n2) / gcd;
```suggestion
int gcd = x, lcm = (n1 * n2) / gcd;

```

2023-10-13 14:10 UTC, closed without merging